import mongoose from "mongoose";

const { Schema } = mongoose;
const model = (name, schema) => mongoose.models[name] || mongoose.model(name, schema);

export const Plan = model("Plan", new Schema({ code:{type:String,unique:true,uppercase:true,trim:true}, name:String, description:String, referencePrice:{type:Number,default:0}, billingCycle:{type:String,enum:["MONTHLY","ANNUAL"],default:"MONTHLY"}, active:{type:Boolean,default:true}, features:[String] },{timestamps:true}));
export const Subscription = model("Subscription", new Schema({ userId:{type:Schema.Types.ObjectId,ref:"User",index:true}, planCode:String, startsAt:Date, endsAt:Date, status:{type:String,enum:["TRIAL","ACTIVE","EXPIRED","CANCELLED","MANUAL"],default:"MANUAL"}, origin:{type:String,enum:["TRIAL","ADMIN","FUTURE_PAYMENT_GATEWAY"],default:"ADMIN"} },{timestamps:true}));
export const Coupon = model("Coupon", new Schema({ code:{type:String,unique:true,uppercase:true,trim:true}, description:String, percentOff:{type:Number,default:0}, amountOff:{type:Number,default:0}, extraTrialDays:{type:Number,default:0}, planCode:String, validUntil:Date, usageLimit:{type:Number,default:0}, usageCount:{type:Number,default:0}, active:{type:Boolean,default:true} },{timestamps:true}));
export const FeatureFlag = model("FeatureFlag", new Schema({ key:{type:String,unique:true}, name:String, description:String, audience:{type:String,enum:["ALL","PREMIUM","ADMINS","TEST_GROUP"],default:"ALL"}, active:{type:Boolean,default:true} },{timestamps:true}));
export const AdminAudit = model("AdminAudit", new Schema({ adminId:{type:Schema.Types.ObjectId,ref:"User"}, adminName:String, targetUserId:{type:Schema.Types.ObjectId,ref:"User"}, targetName:String, action:String, details:Schema.Types.Mixed },{timestamps:true}));
export const Announcement = model("Announcement", new Schema({ title:String, message:String, startsAt:Date, endsAt:Date, audience:{type:String,enum:["ALL","FREE","PLUS","PREMIUM","TRIAL","ADMINS"],default:"ALL"}, active:{type:Boolean,default:true}, createdBy:{type:Schema.Types.ObjectId,ref:"User"} },{timestamps:true}));
export const SupportTicket = model("SupportTicket", new Schema({ userId:{type:Schema.Types.ObjectId,ref:"User",index:true}, subject:String, message:String, category:{type:String,enum:["QUESTION","PROBLEM","SUGGESTION"],default:"QUESTION"}, status:{type:String,enum:["OPEN","IN_PROGRESS","RESOLVED","CLOSED"],default:"OPEN"}, adminReply:String, assignedTo:{type:Schema.Types.ObjectId,ref:"User"} },{timestamps:true}));
export const AdminNote = model("AdminNote", new Schema({ userId:{type:Schema.Types.ObjectId,ref:"User",index:true}, text:String, authorId:{type:Schema.Types.ObjectId,ref:"User"}, authorName:String },{timestamps:true}));
export const AppConfig = model("AppConfig", new Schema({ key:{type:String,unique:true,default:"global"}, productName:{type:String,default:"FinanFlow"}, trialEnabled:{type:Boolean,default:true}, defaultTrialDays:{type:Number,default:7}, trialPlanCode:{type:String,default:"PREMIUM"}, defaultPlanCode:{type:String,default:"FREE"}, registrationsOpen:{type:Boolean,default:true}, maintenanceMode:{type:Boolean,default:false}, maintenanceMessage:{type:String,default:"FinanFlow está em manutenção. Voltaremos em breve."}, globalNoticeEnabled:{type:Boolean,default:false}, globalNotice:{type:String,default:""}, supportEnabled:{type:Boolean,default:true}, couponsEnabled:{type:Boolean,default:true} },{timestamps:true}));

const daysFromNow = (days) => new Date(Date.now()+Number(days)*86400000);
const startOf = (days) => new Date(Date.now()-Number(days)*86400000);
const safeUser = (u) => ({ _id:u._id,name:u.name,email:u.email,profilePhoto:u.profilePhoto||"",role:u.role||"USER",accessStatus:u.accessStatus||"active",lastLoginAt:u.lastLoginAt||null,createdAt:u.createdAt,trialStartedAt:u.trialStartedAt||null,trialEndsAt:u.trialEndsAt||null,trialStatus:u.trialStatus||"NOT_STARTED",planCode:u.planCode||"FREE",blockedAt:u.blockedAt||null });

export async function seedAdminDefaults(){
  await AppConfig.updateOne({key:"global"},{$setOnInsert:{key:"global"}},{upsert:true});
  const plans=[
    {code:"FREE",name:"Gratuito",description:"Recursos essenciais para organização financeira.",referencePrice:0,features:["Lançamentos","Contas"]},
    {code:"PLUS",name:"Plus",description:"Planejamento e relatórios ampliados.",referencePrice:29.9,features:["Lançamentos","Contas","Planejamento","Relatórios"]},
    {code:"PREMIUM",name:"Premium",description:"Experiência completa do FinanFlow.",referencePrice:59.9,features:["Lançamentos","Contas","Planejamento","Modo casal","Relatórios","Exportação","Histórico completo"]},
  ];
  for(const plan of plans) await Plan.updateOne({code:plan.code},{$setOnInsert:plan},{upsert:true});
  const flags=["Modo casal","Planejamento","Relatórios","Exportação","Nova tela em teste"];
  for(const name of flags){const key=name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g,"_");await FeatureFlag.updateOne({key},{$setOnInsert:{key,name,description:`Controle do recurso ${name}`,active:name!=="Nova tela em teste",audience:"ALL"}},{upsert:true});}
}

export function registerAdminRoutes(app,{auth,adminOnly,superAdminOnly,User,Space,Member,Account,Transaction,PurchasePlan,Invite,publicUser,sendRecovery}){
  const audit=async(req,action,target,details={})=>AdminAudit.create({adminId:req.user._id,adminName:req.user.name,targetUserId:target?._id,targetName:target?.name,action,details});
  app.get("/api/platform/config",async(_req,res)=>{const c=await AppConfig.findOne({key:"global"}).lean();res.json({maintenanceMode:c?.maintenanceMode||false,maintenanceMessage:c?.maintenanceMessage,registrationsOpen:c?.registrationsOpen!==false,globalNoticeEnabled:c?.globalNoticeEnabled||false,globalNotice:c?.globalNotice||""});});
  app.get("/api/platform/features",auth,async(req,res)=>{const flags=await FeatureFlag.find().lean();const role=req.user.role||"USER",plan=req.user.planCode||"FREE";res.json({features:Object.fromEntries(flags.map(f=>[f.key,Boolean(f.active&&(f.audience==="ALL"||f.audience==="PREMIUM"&&plan==="PREMIUM"||f.audience==="ADMINS"&&role!=="USER"||f.audience==="TEST_GROUP"&&req.user.trialStatus==="ACTIVE"))]))});});
  app.get("/api/announcements/current",auth,async(req,res)=>{const now=new Date();const userPlan=req.user.planCode||"FREE";const audience=["ALL",userPlan,req.user.role!=="USER"?"ADMINS":null,req.user.trialStatus==="ACTIVE"?"TRIAL":null].filter(Boolean);res.json({announcements:await Announcement.find({active:true,audience:{$in:audience},startsAt:{$lte:now},endsAt:{$gte:now}}).sort({createdAt:-1}).lean()});});
  app.post("/api/support",auth,async(req,res)=>res.status(201).json({ticket:await SupportTicket.create({userId:req.user._id,subject:String(req.body.subject||"").slice(0,160),message:String(req.body.message||"").slice(0,3000),category:req.body.category})}));
  app.get("/api/support/me",auth,async(req,res)=>res.json({tickets:await SupportTicket.find({userId:req.user._id}).sort({createdAt:-1}).lean()}));

  app.get("/api/admin/bootstrap",auth,adminOnly,async(req,res)=>{
    const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),in3=daysFromNow(3),in7=daysFromNow(7);
    const [users,spaces,transactions,accounts,goals,invites,subscriptions,plans,coupons,flags,announcements,tickets,audits,config]=await Promise.all([User.find().select("-passwordHash").lean(),Space.find().lean(),Transaction.find().select("spaceId type createdBy createdAt").lean(),Account.find().select("spaceId createdAt").lean(),PurchasePlan.find().select("spaceId createdBy createdAt").lean(),Invite.find().lean(),Subscription.find().lean(),Plan.find().sort({referencePrice:1}).lean(),Coupon.find().sort({createdAt:-1}).lean(),FeatureFlag.find().sort({name:1}).lean(),Announcement.find().sort({createdAt:-1}).lean(),SupportTicket.find().populate("userId","name email").sort({createdAt:-1}).lean(),AdminAudit.find().sort({createdAt:-1}).limit(200).lean(),AppConfig.findOne({key:"global"}).lean()]);
    const memberCounts=await Member.aggregate([{$group:{_id:"$userId",spaces:{$sum:1}}}]); const sc=new Map(memberCounts.map(x=>[String(x._id),x.spaces]));
    const txCounts=new Map(),goalCounts=new Map(),lastActivity=new Map(); for(const tx of transactions){const id=String(tx.createdBy||"");txCounts.set(id,(txCounts.get(id)||0)+1);if(tx.type==="meta")goalCounts.set(id,(goalCounts.get(id)||0)+1);const d=tx.createdAt;if(d&&(!lastActivity.get(id)||d>lastActivity.get(id)))lastActivity.set(id,d);}
    const clientList=users.map(u=>({...safeUser(u),spaces:sc.get(String(u._id))||0,transactions:txCounts.get(String(u._id))||0,goals:goalCounts.get(String(u._id))||0,lastActivity:lastActivity.get(String(u._id))||u.lastLoginAt||null,isAdmin:["ADMIN","SUPER_ADMIN"].includes(u.role)||String(u.email).toLowerCase()===String(req.user.email).toLowerCase()}));
    const activeRecently=(days)=>new Set(transactions.filter(t=>t.createdAt>=startOf(days)).map(t=>String(t.createdBy))).size;
    const stats={users:users.length,active:users.filter(u=>u.accessStatus!=="blocked").length,blocked:users.filter(u=>u.accessStatus==="blocked").length,newToday:users.filter(u=>u.createdAt>=today).length,new7:users.filter(u=>u.createdAt>=startOf(7)).length,new30:users.filter(u=>u.createdAt>=startOf(30)).length,spaces:spaces.length,individualSpaces:spaces.filter(s=>s.type==="individual").length,coupleSpaces:spaces.filter(s=>s.type==="couple").length,activeCouples:spaces.filter(s=>s.type==="couple"&&invites.some(i=>String(i.spaceId)===String(s._id)&&i.usedAt)).length,pendingInvites:invites.filter(i=>!i.usedAt&&i.expiresAt>now).length,transactions:transactions.length,transactions7:transactions.filter(t=>t.createdAt>=startOf(7)).length,transactions30:transactions.filter(t=>t.createdAt>=startOf(30)).length,accounts:accounts.length,goals:goals.length,activeToday:activeRecently(1),active7:activeRecently(7),active30:activeRecently(30),trials:users.filter(u=>u.trialStatus==="ACTIVE"&&u.trialEndsAt>now).length,trialsToday:users.filter(u=>u.trialStatus==="ACTIVE"&&u.trialEndsAt>=today&&u.trialEndsAt<daysFromNow(1)).length,trials3:users.filter(u=>u.trialStatus==="ACTIVE"&&u.trialEndsAt>=now&&u.trialEndsAt<=in3).length,trials7:users.filter(u=>u.trialStatus==="ACTIVE"&&u.trialEndsAt>=now&&u.trialEndsAt<=in7).length,trialsExpired:users.filter(u=>u.trialStatus==="EXPIRED"||(u.trialStatus==="ACTIVE"&&u.trialEndsAt<=now)).length,subscriptionsActive:subscriptions.filter(s=>["ACTIVE","MANUAL"].includes(s.status)&&(!s.endsAt||s.endsAt>now)).length,subscriptionsManual:subscriptions.filter(s=>s.origin==="ADMIN").length,subscriptionsExpired:subscriptions.filter(s=>s.status==="EXPIRED"||(s.endsAt&&s.endsAt<=now)).length,subscriptionsCancelled:subscriptions.filter(s=>s.status==="CANCELLED").length};
    const monthly=await User.aggregate([{$group:{_id:{$dateToString:{format:"%Y-%m",date:"$createdAt"}},users:{$sum:1}}},{$sort:{_id:1}},{$limit:12}]);
    res.json({me:publicUser(req.user),stats,users:clientList,plans,subscriptions,coupons,flags,announcements,tickets,audits,config,monthly});
  });
  app.get("/api/admin/users/:id",auth,adminOnly,async(req,res)=>{const u=await User.findById(req.params.id).select("-passwordHash").lean();if(!u)return res.status(404).json({message:"Usuário não encontrado."});const memberships=await Member.find({userId:u._id}).select("spaceId").lean(),spaceIds=memberships.map(m=>m.spaceId);const [transactions,accounts,goals,invites,notes,subscription]=await Promise.all([Transaction.countDocuments({createdBy:u._id}),Account.countDocuments({spaceId:{$in:spaceIds}}),PurchasePlan.countDocuments({createdBy:u._id}),Invite.countDocuments({createdBy:u._id,usedAt:{$exists:false}}),AdminNote.find({userId:u._id}).sort({createdAt:-1}).lean(),Subscription.findOne({userId:u._id}).sort({createdAt:-1}).lean()]);res.json({user:{...safeUser(u),spaces:memberships.length,transactions,accounts,goals,pendingInvites:invites},notes,subscription});});
  app.patch("/api/admin/users/:id",auth,adminOnly,async(req,res)=>{const u=await User.findById(req.params.id);if(!u)return res.status(404).json({message:"Usuário não encontrado."});const a=req.body.action;if(a==="block"){u.accessStatus="blocked";u.blockedAt=new Date();u.passwordVersion=(u.passwordVersion||0)+1;}if(a==="unblock"){u.accessStatus="active";u.blockedAt=undefined;}if(a==="sessions")u.passwordVersion=(u.passwordVersion||0)+1;if(a==="role"){if(req.user.role!=="SUPER_ADMIN")return res.status(403).json({message:"Somente SUPER_ADMIN altera roles."});u.role=req.body.role;}if(a==="trial"){const days=Number(req.body.days||7);u.trialStartedAt=u.trialStartedAt||new Date();u.trialEndsAt=req.body.endsAt?new Date(req.body.endsAt):daysFromNow(days);u.trialStatus="ACTIVE";u.accessStatus="trial";u.planCode=req.body.planCode||"PREMIUM";}if(a==="end_trial"){u.trialStatus="CANCELLED";u.accessStatus="active";u.trialEndsAt=new Date();u.planCode="FREE";}if(a==="plan"){u.planCode=req.body.planCode;u.accessStatus="active";}await u.save();await audit(req,a,u,{days:req.body.days,planCode:req.body.planCode,role:req.body.role});res.json({user:safeUser(u)});});
  app.post("/api/admin/users/:id/recovery",auth,adminOnly,async(req,res)=>{const u=await User.findById(req.params.id);if(!u)return res.status(404).json({message:"Usuário não encontrado."});await sendRecovery(u);await audit(req,"password_recovery",u);res.json({message:"Recuperação de senha enviada."});});
  app.post("/api/admin/users/:id/notes",auth,adminOnly,async(req,res)=>{const u=await User.findById(req.params.id);const note=await AdminNote.create({userId:u._id,text:String(req.body.text||"").slice(0,1000),authorId:req.user._id,authorName:req.user.name});await audit(req,"note_created",u);res.status(201).json({note});});
  app.delete("/api/admin/users/:id",auth,superAdminOnly,async(req,res)=>{const u=await User.findById(req.params.id);if(!u)return res.status(404).json({message:"Usuário não encontrado."});if(String(u._id)===String(req.user._id))return res.status(400).json({message:"Você não pode excluir a própria conta."});await audit(req,"user_deleted",u,{email:u.email});const memberships=await Member.find({userId:u._id}).populate("spaceId");for(const membership of memberships){const space=membership.spaceId;if(!space)continue;const count=await Member.countDocuments({spaceId:space._id});if(space.type==="individual"||count<=1){await Promise.all([Transaction.deleteMany({spaceId:space._id}),PurchasePlan.deleteMany({spaceId:space._id}),Account.deleteMany({spaceId:space._id}),Invite.deleteMany({spaceId:space._id}),Member.deleteMany({spaceId:space._id})]);await Space.deleteOne({_id:space._id});}else{await Member.deleteOne({_id:membership._id});if(String(space.ownerId)===String(u._id)){const next=await Member.findOne({spaceId:space._id});if(next)await Space.updateOne({_id:space._id},{ownerId:next.userId});}}}await Promise.all([Subscription.deleteMany({userId:u._id}),SupportTicket.deleteMany({userId:u._id}),AdminNote.deleteMany({userId:u._id}),User.deleteOne({_id:u._id})]);res.json({message:"Conta e dados vinculados excluídos definitivamente."});});
  const crud=(path,Model)=>{app.post(path,auth,adminOnly,async(req,res)=>{const item=await Model.create(req.body);await audit(req,`${Model.modelName}_created`,null,{id:item._id});res.status(201).json({item});});app.patch(`${path}/:id`,auth,adminOnly,async(req,res)=>{const item=await Model.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});await audit(req,`${Model.modelName}_updated`,null,{id:item?._id});res.json({item});});app.delete(`${path}/:id`,auth,adminOnly,async(req,res)=>{await Model.findByIdAndDelete(req.params.id);await audit(req,`${Model.modelName}_deleted`,null,{id:req.params.id});res.json({ok:true});});};
  crud("/api/admin/plans",Plan);crud("/api/admin/coupons",Coupon);crud("/api/admin/announcements",Announcement);crud("/api/admin/features",FeatureFlag);
  app.post("/api/admin/subscriptions",auth,adminOnly,async(req,res)=>{const item=await Subscription.create(req.body);await User.updateOne({_id:item.userId},{planCode:item.planCode});await audit(req,"subscription_created",await User.findById(item.userId),{planCode:item.planCode});res.status(201).json({item});});
  app.patch("/api/admin/subscriptions/:id",auth,adminOnly,async(req,res)=>{const item=await Subscription.findByIdAndUpdate(req.params.id,req.body,{new:true});await audit(req,"subscription_updated",await User.findById(item.userId),req.body);res.json({item});});
  app.patch("/api/admin/tickets/:id",auth,adminOnly,async(req,res)=>{const item=await SupportTicket.findByIdAndUpdate(req.params.id,{...req.body,assignedTo:req.user._id},{new:true});await audit(req,"ticket_updated",null,{id:item?._id,status:item?.status});res.json({item});});
  app.patch("/api/admin/config",auth,superAdminOnly,async(req,res)=>{const item=await AppConfig.findOneAndUpdate({key:"global"},req.body,{new:true,upsert:true,runValidators:true});await audit(req,"config_updated",null,req.body);res.json({config:item});});
  app.get("/api/admin/export/:kind",auth,adminOnly,async(req,res)=>{const maps={users:()=>User.find().select("name email role accessStatus planCode trialStatus trialEndsAt createdAt").lean(),plans:()=>Plan.find().lean(),subscriptions:()=>Subscription.find().lean(),coupons:()=>Coupon.find().lean(),audit:()=>AdminAudit.find().lean(),config:()=>AppConfig.find().lean()};const fn=maps[req.params.kind];if(!fn)return res.status(404).json({message:"Exportação inexistente."});res.json({exportedAt:new Date(),kind:req.params.kind,data:await fn()});});
}
